# Generated by Django 4.2 on 2023-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40)),
                ('quantite', models.IntegerField(default=0)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='./media')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=40)),
                ('profil', models.ImageField(upload_to='')),
            ],
        ),
    ]
